
# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md"]


baseurl:

# the base hostname & protocol for your site
url: "http://localhost:4000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: NX Tactical - Home Page
# Website language
lang: en-US
# Header Title
header-title: Firearms and everything Tactical!
# Header Tagline
headter-tagline: We Sale

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Shop
  url: https://nxtactical.com/index.html#about

# Secondary Buttons
header-secondary-button:
  title: Contact Us
  url: https://nxtactical.com/index.html#contact

#
# This is your email address, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email after you enter below your email and verify that :)
#
email: support@nxtactical.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://nxtactical.setmore.com/
setmore-link: https://nxtactical.setmore.com/

####################################
######  Global Social Links   ######
####################################
youtube: '#'
instagram: 'https://www.instagram.com/nxtactical/'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-img-here.jpg
  author-name: Chris Nauslar
  author-tagline: Blog Author
  author-info: Joint owner of NX Tactical LLC
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: NX Tactical Google Map
map-text-location: Bucharest, Romania
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Welcome to NX Tactical
about-description: NX Tactical is a veteran owned local and online gun shop. Specializing in sales of firearms, accessories, tactical gear, and training. Currently working by appointment only but feel free to browse our site or contact us with any of your questions and we'll be happy to help!"


#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:

# Feature
- title: Clean & Unique Design
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-vector

# Feature
- title: Professional Support
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-help2

# Feature
- title: Pixel Perfect
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-airplay



#####################################
##########  Featured Items ##########
#####################################
portfolio-title: Featured Items
portfolio-description: Check out some of our featured items we have in stock.  You can sort by type, if you see anything you like feel free to contact us.

# Featured Items Grid
#
portfolio-categories: [Lowers, Uppers, Handguards, Barrels, Ammo, Pistol, Rifle, Tactical Gear]
portfolio:

# Item
- title: <span class="thin">Aero Stripped M4E1 Lower FDE</span>
  categories: [Aero, Lowers]
  image: aero/m4e1-stripped-lower-receiver-fde.jpg
  url: '#'

# Item
- title: <span class="thin">Aero Stripped Upper Black</span>
  categories: [Aero, Uppers]
  image: aero/m4e1-threaded-stripped-upper-receiver-black.jpg
  url: '#'

# Item
- title: <span class="thin">Aero Stripped Upper FDE</span>
  categories: [Aero, Uppers]
  image: aero/m4e1-threaded-stripped-upper-receiver-fde.jpg
  url: '#'

# Item
- title: <span class="thin">Aero 9in Handguard Black</span>
  categories: [Aero, Handguards,]
  image: aero/ar15-9-inch-r-one-m-lok-handguard-black-1.jpg
  url: '#'

# Item
- title: <span class="thin">Rosco Barrels</span>
  categories: [Rosco, Barrels,]
  image: rosco/rosco-barrel-14-5.jpg
  url: '#'

# Item
- title: <span class="thin">PCM 223 Bronze 55g</span>
  categories: [PCM, Ammo,]
  image: ammo/pcm-223-ammo.jpg
  url: '#'



#####################################
##########  Core Features  ##########
#####################################
core-title: NX Tactical Core Services
core-description: NX Tactical is here to help you with any of your firearms and tactical needs!

#
# Core Features Left
#
core-features-left:

# Feature
- name: FFL Transfers
  description: Need a controlled item? Send it our way.
  icon:

# Feature
- name: Firearms and Gear
  description: Come check out our inventory or give us a call.
  icon:

# Feature
- name: Firearms Parts
  description: Building a firearm? We can help with the right parts.
  icon:

#
# Core Features Right
#
core-features-right:

# Feature
- name: Ammo
  description: Rang ammo or defence we have it.
  icon:

# Feature
- name: Training
  description: Gun Safety or learning to service your firearm.
  icon:

# Feature
- name: Gunsmith
  description: Need some work done? We are trained and have the tools
  icon:


#####################################
########### Testimonials ############
#####################################
testimonials-title: Testimonials
testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.

#
# Testimonials
#
testimonials:

# Client
- name: Johnatan Doe
  url: http://themeforest.net
  url-text: ThemeForest.net
  avatar: avatar-01.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: themeforest.png

# Client
- name: Adam Smith
  url: http://codecanyon.net
  url-text: CodeCanyon.net
  avatar: avatar-02.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: codecanyon.png

# Client
- name: Irene Warner
  url: http://videohive.net
  url-text: VideoHive.net
  avatar: avatar-03.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: videohive.png

# Client
- name: Richard Ryan
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-04.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: audiojungle.png


#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.


#####################################
############### Team ################
#####################################
team-title: Meet Our Team
team-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Team Members
#
team:

# Team Member
- name: Chris N
  tagline: 
  avatar: avatar-01.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Jim X
  tagline: 
  avatar: avatar-02.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Don X
  tagline:
  avatar: avatar-04.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'


#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Pricing Tables
pricing-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Plan Personal
#
plan-personal-price: $99
plan-personal-offer-1-title: 01 PSD Pack
plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-offer-2-title: 100 Support Tickets
plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-url: '#'

#
# Plan Business
#
plan-business-price: $499
plan-business-offer-1-title: 05 PSD Pack
plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-offer-2-title: 1000 Support Tickets
plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-url: '#'

#
# Plan Ultimate
#
plan-ultimate-price: $999
plan-ultimate-offer-1-title: 10 PSD Pack
plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-offer-2-title: Support Unlimited
plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-url: '#'


#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-number: Phone - 316-749-8835
contact-description: We are Currently working by appointment only as we work through COVID-19 and work to grow our business. Pleae fill out our contact form and well get back with you within 24 hours.


#####################################
#############   Footer   ############
#####################################
footer-description: Retail and online dealer in firearms and tactical gear
footer-copyright-text: NX Tactical LLC
footer-copyright-url: http://www.nxtactical.com
footer-copyright-year: 2020
